// <auto-generated />
using System;
using FeedbackSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FeedbackSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("FeedbackSystem.Models.FeedbackEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("FeedbackEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Great experience. The UI is smooth and easy to use.",
                            Email = "aarav.sharma@example.com",
                            Name = "Aarav Sharma",
                            Rating = 5,
                            SubmittedAtUtc = new DateTime(2026, 4, 20, 9, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Comments = "Form validation works well, and submission is fast.",
                            Email = "priya.nair@example.com",
                            Name = "Priya Nair",
                            Rating = 4,
                            SubmittedAtUtc = new DateTime(2026, 4, 21, 14, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Comments = "Overall good. Would love a dark mode option in future.",
                            Email = "rohit.verma@example.com",
                            Name = "Rohit Verma",
                            Rating = 3,
                            SubmittedAtUtc = new DateTime(2026, 4, 22, 18, 45, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
